# docker compose
version: "3.7"
services:
  postgresql:
    image: postgres:13.2
#    restart: always
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - 5445:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: test13

#to run terminal
# docker-compose --version
# docker-compose -f compose-env.yaml up
# run as daemon
#docker-compose -f compose-env.yaml up -d
#удалить

